import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../auth/models/patient_profile.dart';
import '../../records/models/medical_record.dart';

/// Builds the "Export History" PDF: a printable summary a clinic can file.
///
/// Deliberately plain — no images, no bundled fonts — so it renders the same
/// on any device and stays small enough to send over a weak connection.
abstract final class RecordsPdf {
  RecordsPdf._();

  /// Filename suggested to the OS share/save sheet.
  static String fileName(PatientProfile profile) {
    final now = DateTime.now();
    final stamp = '${now.year}-${now.month.toString().padLeft(2, '0')}-'
        '${now.day.toString().padLeft(2, '0')}';
    final name = profile.fullName.trim().isEmpty
        ? 'patient'
        : profile.fullName.trim().toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '-');
    return 'medicarry-$name-$stamp.pdf';
  }

  static Future<Uint8List> build({
    required PatientProfile profile,
    required List<MedicalRecord> records,
  }) async {
    final document = pw.Document(title: 'MediCarry health summary');
    final generatedAt = DateTime.now();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox()
            : pw.Container(
                alignment: pw.Alignment.centerRight,
                margin: const pw.EdgeInsets.only(bottom: 12),
                child: pw.Text(
                  'MediCarry — ${profile.fullName}',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ),
        build: (context) => [
          _header(profile, generatedAt),
          pw.SizedBox(height: 20),
          _profileSection(profile),
          pw.SizedBox(height: 20),
          _recordsSection(records),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by MediCarry from the patient\'s own records. Verify '
            'clinical details against the source documents before acting on '
            'them.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return document.save();
  }

  static pw.Widget _header(PatientProfile profile, DateTime generatedAt) =>
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Health Summary',
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            profile.fullName.isEmpty ? 'MediCarry patient' : profile.fullName,
            style: const pw.TextStyle(fontSize: 14),
          ),
          pw.SizedBox(height: 2),
          pw.Text(
            'Patient ID ${profile.patientId} • generated '
            '${_formatDateTime(generatedAt)}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.Divider(color: PdfColors.grey400),
        ],
      );

  static pw.Widget _profileSection(PatientProfile profile) {
    final rows = <List<String>>[
      if ((profile.bloodType ?? '').isNotEmpty)
        ['Blood type', profile.bloodType!],
      if ((profile.dateOfBirth ?? '').isNotEmpty)
        ['Date of birth', profile.dateOfBirth!],
      if ((profile.gender ?? '').isNotEmpty) ['Gender', profile.gender!],
      if (profile.allergies.isNotEmpty)
        ['Allergies', profile.allergies.join(', ')],
      if (profile.chronicConditions.isNotEmpty)
        ['Chronic conditions', profile.chronicConditions.join(', ')],
      if ((profile.emergencyContactName ?? '').isNotEmpty)
        [
          'Emergency contact',
          '${profile.emergencyContactName}'
              '${(profile.emergencyContactPhone ?? '').isEmpty ? '' : ' • ${profile.emergencyContactPhone}'}',
        ],
    ];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Patient details'),
        pw.SizedBox(height: 8),
        if (rows.isEmpty)
          pw.Text(
            'No profile details recorded.',
            style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          )
        else
          pw.Table(
            columnWidths: const {
              0: pw.FixedColumnWidth(140),
              1: pw.FlexColumnWidth(),
            },
            children: [
              for (final row in rows)
                pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 3),
                      child: pw.Text(
                        row[0],
                        style: const pw.TextStyle(
                          fontSize: 11,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 3),
                      child: pw.Text(
                        row[1],
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                  ],
                ),
            ],
          ),
      ],
    );
  }

  static pw.Widget _recordsSection(List<MedicalRecord> records) {
    if (records.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Medical records'),
          pw.SizedBox(height: 8),
          pw.Text(
            'No records saved.',
            style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
      );
    }

    // Newest first, matching how the app lists them.
    final sorted = [...records]..sort((a, b) => b.date.compareTo(a.date));

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Medical records (${records.length})'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: ['Date', 'Category', 'Title', 'Provider', 'Detail'],
          cellStyle: const pw.TextStyle(fontSize: 9),
          headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
          cellAlignment: pw.Alignment.topLeft,
          columnWidths: const {
            0: pw.FixedColumnWidth(62),
            1: pw.FixedColumnWidth(62),
            2: pw.FlexColumnWidth(2),
            3: pw.FlexColumnWidth(2),
            4: pw.FlexColumnWidth(3),
          },
          data: [
            for (final record in sorted)
              [
                record.formattedDate,
                record.category.title,
                record.title,
                record.provider,
                record.detail,
              ],
          ],
        ),
      ],
    );
  }

  static pw.Widget _sectionTitle(String text) => pw.Text(
        text,
        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
      );

  static String _formatDateTime(DateTime value) =>
      '${value.day.toString().padLeft(2, '0')}/'
      '${value.month.toString().padLeft(2, '0')}/${value.year} '
      '${value.hour.toString().padLeft(2, '0')}:'
      '${value.minute.toString().padLeft(2, '0')}';
}
